"use client";
import { useMemo, useState } from "react";
import { ArrowRight, Bookmark, Compass, ExternalLink, Flame, Heart, MapPin, Play, Search, Send, Sparkles, Utensils, X } from "lucide-react";

const places = [
 {id:1,name:"Chourasiya Ji Ki Purani Litti Dukan",dish:"Litti Chokha",area:"New Market",pincode:"800001",tag:"Bihar classic",rating:"4.2",price:"₹",image:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85",story:"Old-school litti, smoke, sattu and the kind of stop that feels more Patna than polished."},
 {id:2,name:"Litti Chokha — Original Flame of Bihar",dish:"Litti Chokha",area:"Kankarbagh",pincode:"800020",tag:"Local icon",rating:"4.0",price:"₹",image:"https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=1200&q=85",story:"A focused hunt for the dish Patna visitors keep asking locals about."},
 {id:3,name:"Shyam Chat Stall",dish:"Chaat",area:"Fraser Road",pincode:"800001",tag:"Late-night",rating:"4.7",price:"₹",image:"https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=1200&q=85",story:"A small stall worth knowing when the craving is spicy, tangy and immediate."},
 {id:4,name:"MAANYA STREET FOOD",dish:"Street snacks",area:"Kankarbagh",pincode:"800020",tag:"Neighbourhood",rating:"4.6",price:"₹",image:"https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=1200&q=85",story:"One of the neighbourhood stops surfaced in the current Patna food map."},
 {id:5,name:"Sai Chaat Corner",dish:"Chaat",area:"Khajpura",pincode:"800014",tag:"Evening",rating:"4.5",price:"₹",image:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85",story:"An evening chaat hunt around Khajpura, built for spontaneous detours."},
 {id:6,name:"CK Litti Chokha",dish:"Litti Chokha",area:"Boring Road",pincode:"800001",tag:"Breakfast",rating:"4.1",price:"₹",image:"https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=1200&q=85",story:"A Boring Road option for the days when the craving starts before noon."}
];
const chips=["Litti Chokha","Momo","Chaat","Biryani","Rolls","Sweets","Coffee","Hidden Gems"];
const reels=[["PATNA FOOD MAP","Street food worth crossing town for","YouTube"],["BORING ROAD","What to eat. What to skip.","Instagram"],["KHAO GALI","Old Museum Road food crawl","YouTube"],["LITTI HUNT","Bihar's smoky classic, decoded","Instagram"]];

export default function Home(){
 const [query,setQuery]=useState(""); const [active,setActive]=useState("All"); const [hunt,setHunt]=useState(false); const [saved,setSaved]=useState<number[]>([]);
 const filtered=useMemo(()=>places.filter(p=>active==="All" || p.dish===active || p.area===active || p.tag===active).filter(p=>(p.name+" "+p.dish+" "+p.area+" "+p.pincode).toLowerCase().includes(query.toLowerCase())),[active,query]);
 const toggle=(id:number)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 return <main>
  <nav className="nav"><div className="brand"><span className="brandMark">CH</span><div><b>CRAVE HUNT</b><small>PATNA</small></div></div><div className="navlinks"><a href="#discover">Discover</a><a href="#hunts">Crave Hunts</a><a href="#reels">Food Reels</a></div><button className="huntBtn" onClick={()=>setHunt(true)}>List a craving <ArrowRight size={16}/></button></nav>
  <section className="hero"><div className="heroNoise"/><div className="heroCopy"><p className="eyebrow"><span/> PATNA'S STREET FOOD INTELLIGENCE</p><h1>What's your<br/><i>craving?</i></h1><p className="lede">Not another restaurant directory. A living map of the food Patna people actually chase.</p><div className="search"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a dish, place, area or pincode…"/><kbd>⌘ K</kbd></div><div className="micro"><span><MapPin size={13}/> Patna, Bihar</span><span><Flame size={13}/> 100% craving-led</span><span><Sparkles size={13}/> Human reviewed</span></div></div><div className="heroPlate"><div className="plateGlow"/><div className="foodEmoji">🥟</div><div className="scribble">GO<br/>HUNT<br/>IT.</div><div className="heroCard"><small>TONIGHT'S HUNT</small><b>Street food after 8 PM</b><span>Fraser Road · Maurya Lok · Boring Road</span></div></div></section>
  <section className="section" id="discover"><div className="sectionHead"><div><p className="eyebrow">DISCOVER BY CRAVING</p><h2>Say the food.<br/>We'll find the trail.</h2></div><p className="muted">Browse by dish, neighbourhood, pincode, mood, time or whatever is currently ruining your ability to think about anything else.</p></div><div className="chips"><button className={active==="All"?"active":""} onClick={()=>setActive("All")}>Everything</button>{chips.map(c=><button key={c} className={active===c?"active":""} onClick={()=>setActive(c)}>{c}</button>)}</div><div className="grid">{filtered.map((p,i)=><article className="foodCard" key={p.id}><div className="photo" style={{backgroundImage:"url("+p.image+")"}}><span className="tag">{p.tag}</span><button className="save" onClick={()=>toggle(p.id)}>{saved.includes(p.id)?<Heart fill="currentColor" size={17}/>:<Bookmark size={17}/>}</button><span className="price">{p.price}</span></div><div className="cardBody"><div className="meta"><span>{p.dish}</span><span>★ {p.rating}</span></div><h3>{p.name}</h3><p>{p.story}</p><div className="location"><MapPin size={14}/>{p.area} · {p.pincode}<ArrowRight size={15}/></div></div></article>)}</div>{filtered.length===0&&<div className="empty">No hunt found yet. That is exactly the kind of gap Crave Hunt should fill.</div>}</section>
  <section className="dark" id="hunts"><div className="huntVisual"><div className="circle">CRAVE<br/>HUNT<br/><span>∞</span></div><div className="orbit o1">LITTI</div><div className="orbit o2">MOMO</div><div className="orbit o3">CHAAT</div></div><div className="huntCopy"><p className="eyebrow">THE FEATURE THAT BUILDS THE DATABASE</p><h2>Can't find<br/><i>your craving?</i></h2><p>Tell us exactly what you're hunting. Dish. Area. A reel you saw. A stall your friend swears by. We'll investigate it, review it and decide whether it earns a place on the map.</p><button className="creamBtn" onClick={()=>setHunt(true)}>Start a Crave Hunt <Send size={16}/></button><small>No anonymous star spam. No pay-to-win rankings. Just better food intelligence.</small></div></section>
  <section className="section reels" id="reels"><div className="sectionHead"><div><p className="eyebrow">WATCH BEFORE YOU WALK</p><h2>Food content,<br/>without the doomscroll.</h2></div><p className="muted">One place for the reels and videos that actually help you decide where to eat. Categorised by dish, place, area and hunt.</p></div><div className="reelGrid">{reels.map((r,i)=><a className="reel" href="#" key={r[0]} onClick={e=>e.preventDefault()}><div className="play"><Play fill="currentColor" size={17}/></div><div><small>{r[2]} · {String(i+1).padStart(2,"0")}</small><h3>{r[0]}</h3><p>{r[1]}</p></div><ExternalLink size={16}/></a>)}</div></section>
  <footer><div className="brand"><span className="brandMark">CH</span><div><b>CRAVE HUNT</b><small>PATNA</small></div></div><p>A community-built food intelligence layer for Patna.</p><span>v0.1 · built for the hunt</span></footer>
  {hunt&&<div className="modal" onClick={()=>setHunt(false)}><div className="modalCard" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setHunt(false)}><X/></button><p className="eyebrow">SUBMIT A CRAVING</p><h2>What are you<br/><i>hunting?</i></h2><p className="muted">Send us the craving. We'll do the digging.</p><input placeholder="e.g. best chicken roll near Kankarbagh"/><input placeholder="Area / pincode (optional)"/><textarea placeholder="Drop a reel, YouTube link, stall name, or tell us why you think it deserves a hunt…"/><button className="submit" onClick={()=>setHunt(false)}>Send the hunt <ArrowRight size={16}/></button></div></div>}
 </main>
}